### ISSUE TITLE
Failed to Export

### ISSUE THREAD

**Issue by sime0n1** [DeveloperGuilliman/CardEditor#1]
When Exporting custom cards i get the error "IllegalArgumentException : U+000A ('controlLF') is not available in this font Times-Italic encoding: WinAnsiEncoding "

I went through my list and couldn't find any italics also googled the error but I'm super computer illiterate.

Thanks awesome job.

**Comment by DeveloperGuilliman** [comment]
Hi.
The problem is a bug with texts with newlines. The pdf generator tries to generate himself the newlines and breaks when any text field has a newline.
The workaround is to erase all newlines and use spaces. Will be fixed in the next version.

**Comment by DeveloperGuilliman** [comment]
Bug fixed in the new 0.2.0 version.
[https://github.com/DeveloperGuilliman/CardEditor/releases/tag/0.2.0](url)

**Comment by sime0n1** [comment]
mate absolute legend thanks
