### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by alfonsolopez141** [DeveloperGuilliman/CardEditor#2]
Hello, 

how can I run the program?

I download the folders in zip, I extract them but I don't know how to execute them.

**Comment by DeveloperGuilliman** [comment]
This is a Java 8 Application without the standalone JRE (this is a future point to upgrade)
To run it, you will need to have installed a Java Runtime Enviroment (JRE)
[https://www.java.com/es/download/manual.jsp](url)
With this, you will be able to execute .jar files as executables.

**Comment by alfonsolopez141** [comment]
I put the link and I get the java page saying '' sorry, we have not found the requested document '' :/

**Comment by alfonsolopez141** [comment]
I have java installed but it can't find the application, it's strange.

**Comment by DeveloperGuilliman** [comment]
Try the new release. It includes a .bat to execute it on Windows and a .sh to execute it on Linux.
[https://github.com/DeveloperGuilliman/CardEditor/releases/tag/0.2.0.1](url)

**Comment by alfonsolopez141** [comment]
Yeah, it runs,  thanks¡¡
